package yousei.util;



/**
 * Created by s-sumi on 2016/07/12.
 */
public class NodeClasses4Java extends NodeClasses {
    public NodeClasses4Java() {
        this.dictionary.put("ANONYMOUS_CLASS_DECLARATION",1);
        this.dictionary.put("ARRAY_ACCESS",2);
        this.dictionary.put("ARRAY_CREATION",3);
        this.dictionary.put("ARRAY_INITIALIZER",4);
        this.dictionary.put("ARRAY_TYPE",5);
        this.dictionary.put("ASSERT_STATEMENT",6);
        this.dictionary.put("ASSIGNMENT",7);
        this.dictionary.put("BLOCK",8);
        this.dictionary.put("BOOLEAN_LITERAL",9);
        this.dictionary.put("BREAK_STATEMENT",10);
        this.dictionary.put("CAST_EXPRESSION",11);
        this.dictionary.put("CATCH_CLAUSE",12);
        this.dictionary.put("CHARACTER_LITERAL",13);
        this.dictionary.put("CLASS_INSTANCE_CREATION",14);
        this.dictionary.put("COMPILATION_UNIT",15);
        this.dictionary.put("CONDITIONAL_EXPRESSION",16);
        this.dictionary.put("CONSTRUCTOR_INVOCATION",17);
        this.dictionary.put("CONTINUE_STATEMENT",18);
        this.dictionary.put("DO_STATEMENT",19);
        this.dictionary.put("EMPTY_STATEMENT",20);
        this.dictionary.put("EXPRESSION_STATEMENT",21);
        this.dictionary.put("FIELD_ACCESS",22);
        this.dictionary.put("FIELD_DECLARATION",23);
        this.dictionary.put("FOR_STATEMENT",24);
        this.dictionary.put("IF_STATEMENT",25);
        this.dictionary.put("IMPORT_DECLARATION",26);
        this.dictionary.put("INFIX_EXPRESSION",27);
        this.dictionary.put("INITIALIZER",28);
        this.dictionary.put("JAVADOC",29);
        this.dictionary.put("LABELED_STATEMENT",30);
        this.dictionary.put("METHOD_DECLARATION",31);
        this.dictionary.put("METHOD_INVOCATION",32);
        this.dictionary.put("NULL_LITERAL",33);
        this.dictionary.put("NUMBER_LITERAL",34);
        this.dictionary.put("PACKAGE_DECLARATION",35);
        this.dictionary.put("PARENTHESIZED_EXPRESSION",36);
        this.dictionary.put("POSTFIX_EXPRESSION",37);
        this.dictionary.put("PREFIX_EXPRESSION",38);
        this.dictionary.put("PRIMITIVE_TYPE",39);
        this.dictionary.put("QUALIFIED_NAME",40);
        this.dictionary.put("RETURN_STATEMENT",41);
        this.dictionary.put("SIMPLE_NAME",42);
        this.dictionary.put("SIMPLE_TYPE",43);
        this.dictionary.put("SINGLE_VARIABLE_DECLARATION",44);
        this.dictionary.put("STRING_LITERAL",45);
        this.dictionary.put("SUPER_CONSTRUCTOR_INVOCATION",46);
        this.dictionary.put("SUPER_FIELD_ACCESS",47);
        this.dictionary.put("SUPER_METHOD_INVOCATION",48);
        this.dictionary.put("SWITCH_CASE",49);
        this.dictionary.put("SWITCH_STATEMENT",50);
        this.dictionary.put("SYNCHRONIZED_STATEMENT",51);
        this.dictionary.put("THIS_EXPRESSION",52);
        this.dictionary.put("THROW_STATEMENT",53);
        this.dictionary.put("TRY_STATEMENT",54);
        this.dictionary.put("TYPE_DECLARATION",55);
        this.dictionary.put("TYPE_DECLARATION_STATEMENT",56);
        this.dictionary.put("TYPE_LITERAL",57);
        this.dictionary.put("VARIABLE_DECLARATION_EXPRESSION",58);
        this.dictionary.put("VARIABLE_DECLARATION_FRAGMENT",59);
        this.dictionary.put("VARIABLE_DECLARATION_STATEMENT",60);
        this.dictionary.put("WHILE_STATEMENT",61);
        this.dictionary.put("INSTANCEOF_EXPRESSION",62);
        this.dictionary.put("LINE_COMMENT",63);
        this.dictionary.put("BLOCK_COMMENT",64);
        this.dictionary.put("TAG_ELEMENT",65);
        this.dictionary.put("TEXT_ELEMENT",66);
        this.dictionary.put("MEMBER_REF",67);
        this.dictionary.put("METHOD_REF",68);
        this.dictionary.put("METHOD_REF_PARAMETER",69);
        this.dictionary.put("ENHANCED_FOR_STATEMENT",70);
        this.dictionary.put("ENUM_DECLARATION",71);
        this.dictionary.put("ENUM_CONSTANT_DECLARATION",72);
        this.dictionary.put("TYPE_PARAMETER",73);
        this.dictionary.put("PARAMETERIZED_TYPE",74);
        this.dictionary.put("QUALIFIED_TYPE",75);
        this.dictionary.put("WILDCARD_TYPE",76);
        this.dictionary.put("NORMAL_ANNOTATION",77);
        this.dictionary.put("MARKER_ANNOTATION",78);
        this.dictionary.put("SINGLE_MEMBER_ANNOTATION",79);
        this.dictionary.put("MEMBER_VALUE_PAIR",80);
        this.dictionary.put("ANNOTATION_TYPE_DECLARATION",81);
        this.dictionary.put("ANNOTATION_TYPE_MEMBER_DECLARATION",82);
        this.dictionary.put("MODIFIER",83);
        this.dictionary.put("UNION_TYPE",84);
        this.dictionary.put("DIMENSION",85);
        this.dictionary.put("LAMBDA_EXPRESSION",86);
        this.dictionary.put("INTERSECTION_TYPE",87);
        this.dictionary.put("NAME_QUALIFIED_TYPE",88);
        this.dictionary.put("CREATION_REFERENCE",89);
        this.dictionary.put("EXPRESSION_METHOD_REFERENCE",90);
        this.dictionary.put("SUPER_METHOD_REFERENCE",91);
        this.dictionary.put("TYPE_METHOD_REFERENCE",92);
    }
}
